# Generated by Django 4.2.23 on 2025-09-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrequest',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
    ]
