# Generated by Django 4.2.23 on 2025-09-06 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('B_token', models.CharField(max_length=30)),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='mpesa_transactions',
            fields=[
                ('slug', models.SlugField(default=uuid.uuid4, max_length=255, unique=True)),
                ('Transaction_code', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('MerchantRequestID', models.CharField(max_length=50, null=True)),
                ('CheckoutRequestID', models.CharField(max_length=50, null=True)),
                ('ResponseCode', models.CharField(max_length=30, null=True)),
                ('ResponseDescription', models.CharField(max_length=30, null=True)),
                ('CustomerMessage', models.CharField(max_length=30, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('amount', models.CharField(max_length=15, null=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('account_reference', models.CharField(max_length=30)),
                ('transaction_desc', models.CharField(max_length=30)),
                ('occassion', models.CharField(max_length=30)),
                ('is_finished', models.BooleanField(default=False)),
                ('is_successful', models.BooleanField(default=False)),
                ('timestamp', models.IntegerField(null=True)),
                ('trans_id', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='UserPay')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'get_latest_by': 'paid_at',
            },
        ),
    ]
