# Generated by Django 4.2.23 on 2025-09-06 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicReg',
            fields=[
                ('clinic_code', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('clinic_name', models.CharField(max_length=120, null=True)),
                ('clinic_email', models.CharField(max_length=120)),
                ('clinic_logo', models.ImageField(default='icon/bondijunction_dentalclinic_logo-300x258.jpg', null=True, upload_to='sp/')),
                ('clinic_url', models.URLField(default='smileslot.onrender.com', max_length=120)),
                ('mobile_number', models.CharField(max_length=15)),
                ('reg_date_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('clinic_location', models.CharField(max_length=120, null=True)),
                ('registered', models.BooleanField(default=False)),
                ('member', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_clinic', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('slots_per_hour', models.PositiveIntegerField(default=4)),
            ],
            options={
                'unique_together': {('start', 'end')},
            },
        ),
        migrations.CreateModel(
            name='Wednesday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.clinicreg')),
                ('time_range', models.ManyToManyField(to='Dashboard.timerange')),
            ],
        ),
        migrations.CreateModel(
            name='Tuesday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.clinicreg')),
                ('time_range', models.ManyToManyField(to='Dashboard.timerange')),
            ],
        ),
        migrations.CreateModel(
            name='Thursday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.clinicreg')),
                ('time_range', models.ManyToManyField(to='Dashboard.timerange')),
            ],
        ),
        migrations.CreateModel(
            name='Sunday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.clinicreg')),
                ('time_range', models.ManyToManyField(to='Dashboard.timerange')),
            ],
        ),
        migrations.CreateModel(
            name='Saturday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.clinicreg')),
                ('time_range', models.ManyToManyField(to='Dashboard.timerange')),
            ],
        ),
        migrations.CreateModel(
            name='Monday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.clinicreg')),
                ('time_range', models.ManyToManyField(to='Dashboard.timerange')),
            ],
        ),
        migrations.CreateModel(
            name='Friday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.clinicreg')),
                ('time_range', models.ManyToManyField(to='Dashboard.timerange')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_reviews', to='Dashboard.clinicreg')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('clinic', 'patient')},
            },
        ),
    ]
