# Generated by Django 4.2.23 on 2025-09-21 10:11

import Accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=Accounts.models.generate_username, max_length=50),
        ),
    ]
