# Generated by Django 4.2.23 on 2025-09-06 12:27

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('soshi_user', models.CharField(max_length=100)),
                ('blog_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('blog_title', models.CharField(max_length=250)),
                ('blog_subtitle', models.CharField(max_length=250)),
                ('caption', ckeditor.fields.RichTextField(blank=True)),
                ('blog_image', models.ImageField(default='icon/bondijunction_dentalclinic_logo-300x258.jpg', upload_to='blog_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagetitle', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('aboutus', models.TextField()),
                ('email', models.EmailField(max_length=200)),
                ('mobilenumber', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
