# Generated by Django 4.2.23 on 2025-09-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0002_tenant_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='subdomain',
            field=models.CharField(default='mboa', max_length=50),
            preserve_default=False,
        ),
    ]
