# Generated by Django 4.2.23 on 2025-09-06 12:27

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('slots', '0001_initial'),
        ('Dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('diagnosis', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('medications', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('notes', ckeditor.fields.RichTextField(blank=True)),
                ('booking_status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(limit_choices_to={'status': 'Approved'}, on_delete=django.db.models.deletion.CASCADE, related_name='booking_prescription', to='slots.appointment')),
                ('clinic', models.ForeignKey(limit_choices_to={'registered': True}, on_delete=django.db.models.deletion.CASCADE, related_name='booking_clinic', to='Dashboard.clinicreg')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_prescriptions_given', to='slots.staffmember')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_prescriptions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('doctor', 'booking', 'patient', 'clinic')},
            },
        ),
    ]
